[package]
name = "debt_calculator"
version = "0.1.0"
authors = ["Mathias Iversen <mathias.iversen@danielwellington.com>"]
edition = "2018"
licence = "MIT"

[dependencies]
structopt = "0.3.5"
Lotus = "0.2.1"
chrono = "0.4"
