[package]
name = "html-in-rust"
version = "0.1.0"
authors = ["Mathias Iversen <mathias.iversen@danielwellington.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.5"
Lotus = "0.2.1"
